[build]
  base = ""  # No subfolder, since everything is in the root
  publish = "build"  # The folder Netlify deploys after building
  command = "npm install && npm run build"  # Build the project

[build.environment]
  NODE_VERSION = "20"  # Ensure correct Node.js version
