"""Initial migration

Revision ID: cdc0f4abaf86
Revises: eb69b6142c9e
Create Date: 2025-03-21 14:41:34.894592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc0f4abaf86'
down_revision = 'eb69b6142c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.drop_column('vote_count')
        batch_op.drop_column('category')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
